package peng.mou.kobron;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.data.redis.core.RedisTemplate;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class RedisFirstApplication {

    public static void main(String[] args) {
        SpringApplication.run(RedisFirstApplication.class, args);
    }

//    @Bean
//    public RedisTemplate redisTemplate(){
//
//        return new RedisTemplate();
//    }
}
